*   Nome: Eduardo Lopes de Oliveira
*   RA: 161490336



# Operadores Binário

In [ ]:
a = 0b0011 # 3 na base 10
b = 0b0101 # 5 na base 10

# Operador AND
result = a & b

# Operador OR
result = a | b

# Operador NOT
result = -a

# Operador XOR
result = a ^ b

# Operador 'desloque 2 dígitos para a esquerda'
result = a << 2

# Operador 'desloque 2 dígitos para a direita'
result = 0b1100 >> 2

print(bin(result))

0b11


## Exercício - Operadores Binários


*   Transforme o número binário '0b0100' em '0b0010' com uma operação
*   Transforme o número binário '0b0001' em '0b1011' com duas operações

OBS: Somente as variáveis '0b0000' e '0b1111' podem ser usadas para realizar as operações.



In [ ]:
a = 0b0100
b = 0b0001

# Primeiro item
op1 = a >> 1
print('O resultado do primeiro item: ', bin(op1))

# Segundo item
op2 = b << 2
op3 = op2 ^ 0b1111
print('O resultado do segundo item: ', bin(op3))

O resultado do primeiro item:  0b10
O resultado do segundo item:  0b1011


## Operadores Binários nas Declarações Condicionais?

In [ ]:
if (5 < 3) | (1 > 0.5):
  print('yes!')

yes!


# Biblioteca NumPy

In [ ]:
import numpy as np
print(np.pi)

3.141592653589793


In [ ]:
# Definindo-se um array com NumPy
a = np.array([1, 2, 3, 4, 5])

# Definindo-se uma matriz em NumPy
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
lista = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

a = np.asarray(lista)

print(a[1,1])
print(a[0][0])
print(a[0:2, 0:2])

5
1
[[1 2]
 [4 5]]


## Exercício - NumPy e Laço For

Desenvolva um algoritmo que adiciona valores aletórios aos elementos de um array de 10 posições. A cada iteração, verifique se a média ou o desvio padrão de todos os elementos do array é maior do que 3. Em caso positivo, imprima os valores máximo, mínimo, a média e o desvio padrão, e quebre o laço com break

In [ ]:
import random

lista = np.array([random.randint(0, 10), random.randint(0, 10), random.randint(0, 10), random.randint(0, 10), random.randint(0, 10),
                 random.randint(0, 10), random.randint(0, 10), random.randint(0, 10), random.randint(0, 10), random.randint(0, 10)])

media = np.mean(lista)
desvio = np.std(lista)
print('A lista ficou: ', lista)

if (media > 3) | (desvio > 3):
  print('O valor máximo da lista: ', np.max(lista))
  print('O valor mínimo da lista: ', np.min(lista))
  print('A média da lista: ', media)
  print('O desvio padrão da lista: ', desvio)

else:
  print('Não atendeu os requisitos, a média deu ', media, ' e o desvio deu ', desvio)