

*   **Nome:** Eduardo Lopes de Oliveira
*   **RA:** 161490336


# Exercício - Exercício sem usar o laço "For", usando "While"

Desenvolva um algoritmo que imprima uma matriz com o número de linhas e de colunas variável (posso mudar o número de linhas ou colunas mudando-se variáveis numéricos). Adicione elementos à essa matriz, elemento a elemento, sendo que os elementos a serem adicionados sigam um função quadrática "f(x) = x**2", com argumento "x" indo de 0 à 10. Por exemplo, uma matriz 2x2 ficará como segue [[0 11.1][44.4 100]]

Dica: Utilize um contador, por exemplo "count", que iniciará em zero e sera acrescido de 1 em 1, para contar quantos itens já foram adicionados à matriz, e servir de argumentos para a função 'f[n]'.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

linhas = int(input('Qual o número de linhas e colunas? '))
colunas = linhas
matriz = np.zeros((linhas, colunas))
x = np.linspace(0, 10, colunas**2)
count = 0

linha = 0
coluna = 0

while linha < linhas:
    while coluna < colunas:
        matriz[linha, coluna] = round(x[count]**2, 2)
        count += 1
        coluna += 1
    linha += 1
    coluna = 0

print(matriz)

Qual o número de linhas e colunas? 5
[[  0.     0.17   0.69   1.56   2.78]
 [  4.34   6.25   8.51  11.11  14.06]
 [ 17.36  21.01  25.    29.34  34.03]
 [ 39.06  44.44  50.17  56.25  62.67]
 [ 69.44  76.56  84.03  91.84 100.  ]]


# Exercício Avançado de "For"

Insira elementos em uma matriz 3x3, item a item, aleatoriamente (com valores de 1 a 10), até que a média dos valores de matriz ultrapasse 4. Se isso acontecer, pare de inserir os elementos, e imprima a matriz ao final do programa. Para cada linha ou coluna completa, caso a condição "média da matriz > 4" não tenha sido satisfeita, imprima qual a linha (ou coluna) que foi completada. Caso toda a matriz tenha sido completada, imprima "Matriz concluída!".

OBS: Não utilize novos "if" para imprimir se a coluna, linha ou matriz coluna utilize os "else" das condicionais já definidas, ou utilize "elif".

## Exercício base da Aula 8:

In [ ]:
import random
import numpy as np

# Cria uma matriz 3x3 de zeros
matriz = np.zeros((3, 3))

# Preenche a matriz com números aleatórios de 0 a 10
for linha in range(3):
    for coluna in range(3):
        novo_valor = random.randint(1, 10)
        matriz[linha, coluna] = novo_valor
        media_atual = np.mean(matriz)
        print(f"Novo valor: {novo_valor}, Média: {media_atual}")

        if media_atual > 3:
            print("\nMédia atual ", media_atual, " é maior que 3. Parando.")
            print("Valor Mínimo: ", np.min(matriz))
            print("Valor Máximo: ", np.max(matriz))
            print("Média: ", np.mean(matriz))
            print("Desvio Padrão: ", np.std(matriz))
            break
    else:
        continue  # Executa se o loop interno não for interrompido
    break  # Executa se o loop interno for interrompido

print("\nMatriz Final:")
print(matriz)

Novo valor: 1, Média: 0.1111111111111111
Novo valor: 4, Média: 0.5555555555555556
Novo valor: 6, Média: 1.2222222222222223
Novo valor: 3, Média: 1.5555555555555556
Novo valor: 10, Média: 2.6666666666666665
Novo valor: 5, Média: 3.2222222222222223

Média atual  3.2222222222222223  é maior que 3. Parando.
Valor Mínimo:  0.0
Valor Máximo:  10.0
Média:  3.2222222222222223
Desvio Padrão:  3.2241373618993134

Matriz Final:
[[ 1.  4.  6.]
 [ 3. 10.  5.]
 [ 0.  0.  0.]]


## Tentativa

In [ ]:
import random
import numpy as np

# Cria uma matriz 3x3 de zeros
matriz = np.zeros((3, 3))
count = 1

# Preenche a matriz com números aleatórios de 0 a 10
for linha in range(3):
    for coluna in range(3):
        novo_valor = random.randint(1, 10)
        matriz[linha, coluna] = novo_valor
        media_atual = np.mean(matriz)
        print(f"Novo valor: {novo_valor}, Média: {media_atual}")

        if media_atual > 4:
            print("\nMatriz concluída! A média é", media_atual)
            break

    else:
      print("Linha ", count, "completa")
      count += 1
      continue
    break

print("\nMatriz Final")
print(matriz)


Novo valor: 8, Média: 0.8888888888888888
Novo valor: 4, Média: 1.3333333333333333
Novo valor: 8, Média: 2.2222222222222223
Linha  1 completa
Novo valor: 7, Média: 3.0
Novo valor: 8, Média: 3.888888888888889
Novo valor: 3, Média: 4.222222222222222

Matriz concluída! A média é 4.222222222222222

Matriz Final
[[8. 4. 8.]
 [7. 8. 3.]
 [0. 0. 0.]]


In [ ]:
import random
import numpy as np

# Cria uma matriz 3x3 de zeros
matriz = np.zeros((3, 3))
count = 1

# Preenche a matriz com números aleatórios de 0 a 10
for linha in range(3):
    for coluna in range(3):
        novo_valor = random.randint(1, 10)
        matriz[linha, coluna] = novo_valor
        media_atual = np.mean(matriz)
        print(f"Novo valor: {novo_valor}, Média: {media_atual}")

        if media_atual > 4:
            print("\nMatriz concluída! A média é", media_atual)
            break

        elif matriz[0][2]>0:
            print("Linha 1 completa")
            continue

        elif matriz[2][0]>0:
            print("Coluna 1 completa")
            continue

        elif matriz[1][2]>0:
            print("Linha 2 completa")
            continue

        elif matriz[2][1]>0:
            print("Coluna 2 completa")
            continue

        elif matriz[2][2]>0:
            print("Linha 3 completa")
            print("Coluna 3 completa")
            continue

    else:
        continue
    break

print("\nMatriz Final")
print(matriz)


Novo valor: 6, Média: 0.6666666666666666
Novo valor: 3, Média: 1.0
Novo valor: 4, Média: 1.4444444444444444
Linha 1 completa
Novo valor: 9, Média: 2.4444444444444446
Linha 1 completa
Novo valor: 5, Média: 3.0
Linha 1 completa
Novo valor: 7, Média: 3.7777777777777777
Linha 1 completa
Novo valor: 4, Média: 4.222222222222222

Matriz concluída! A média é 4.222222222222222

Matriz Final
[[6. 3. 4.]
 [9. 5. 7.]
 [4. 0. 0.]]


In [ ]:
import random
import numpy as np

# Cria uma matriz 3x3 de zeros
matriz = np.zeros((3, 3))

# Preenche a matriz com números aleatórios de 0 a 10
for linha in range(3):
    for coluna in range(3):
        novo_valor = random.randint(1, 10)
        matriz[linha, coluna] = novo_valor
        media_atual = np.mean(matriz)
        print(f"Novo valor: {novo_valor}, Média: {media_atual}")

        if media_atual > 4:
            print("\nMatriz concluída! A média é", media_atual)
            break

        if linha == 2 and coluna == 2:
            print("Linha 3 completa")
            print("Coluna 3 completa")

        elif linha == 0 and coluna == 2:
            print("Linha 1 completa")

        elif linha == 1 and coluna == 2:
            print("Linha 2 completa")

        elif linha == 2 and coluna == 0:
            print("Coluna 1 completa")

        elif linha == 2 and coluna == 1:
            print("Coluna 2 completa")

print("\nMatriz Final")
print(matriz)

Novo valor: 2, Média: 0.2222222222222222
Novo valor: 5, Média: 0.7777777777777778
Novo valor: 3, Média: 1.1111111111111112
Linha 1 completa
Novo valor: 3, Média: 1.4444444444444444
Novo valor: 9, Média: 2.4444444444444446
Novo valor: 9, Média: 3.4444444444444446
Linha 2 completa
Novo valor: 1, Média: 3.5555555555555554
Coluna 1 completa
Novo valor: 3, Média: 3.888888888888889
Coluna 2 completa
Novo valor: 2, Média: 4.111111111111111

Matriz concluída! A média é 4.111111111111111

Matriz Final
[[2. 5. 3.]
 [3. 9. 9.]
 [1. 3. 2.]]


In [ ]:
import random
import numpy as np

# Cria uma matriz 3x3 de zeros
matriz = np.zeros((3, 3))
flag = False

# Preenche a matriz com números aleatórios de 0 a 10
for linha in range(3):
    for coluna in range(3):
        novo_valor = random.randint(1, 10)
        matriz[linha, coluna] = novo_valor
        media_atual = np.mean(matriz)
        print(f"Novo valor: {novo_valor}, Média: {media_atual}")

        if media_atual > 4:
            print("\nMatriz concluída! A média é", media_atual)
            flag = True
            break
    else:
        print("Linha", linha+1, "completa!")

    if flag == True:
      break

if linha == 2:
    print("Coluna", coluna+1, "completa!")

print("\nMatriz Final")
print(matriz)

Novo valor: 5, Média: 0.5555555555555556
Novo valor: 1, Média: 0.6666666666666666
Novo valor: 1, Média: 0.7777777777777778
Linha 1 completa!
Novo valor: 5, Média: 1.3333333333333333
Novo valor: 9, Média: 2.3333333333333335
Novo valor: 8, Média: 3.2222222222222223
Linha 2 completa!
Novo valor: 1, Média: 3.3333333333333335
Novo valor: 10, Média: 4.444444444444445

Matriz concluída! A média é 4.444444444444445
Coluna 2 completa!

Matriz Final
[[ 5.  1.  1.]
 [ 5.  9.  8.]
 [ 1. 10.  0.]]
