# Cabeçalho

*   **Nome:** Eduardo Lopes de Oliveira
*   **RA:** 161490336



#Exercício - NumPy e Laço For


Desenvolva um programa que crie uma matriz 3x3, elemento a elemento, com valores aletórios de 1 a 10. A cada uma das 9 iterações, verifique se a média dos elementos da matriz é maior do que três. Se isso acontecer, imprima na tela o valor mínimo, máximo, a média e o desvio padrão dos elementos da matriz, imprima a matriz inteira e pare a execução do programa

## Primeira tentativa

In [ ]:
import random
import numpy as np

matriz = []

for i in range(0, 3):
    linha = []
    for j in range(0, 3):
        linha.append(random.randint(1, 10))
    matriz.append(linha)

    if np.mean(matriz) > 3:
        saio_do_programa = True;
        print("Média dos elementos é maior que três.")
        print("Valor Mínimo:", np.min(matriz))
        print("Valor Máximo:", np.max(matriz))
        print("Média:", np.mean(matriz))
        print("Desvio Padrão:", np.std(matriz))
        print("Matriz:")
        for linha in matriz:
            print(linha)
        #break


print("Matriz final:")
for linha in matriz:
    print(linha)

Média dos elementos é maior que três.
Valor Mínimo: 3
Valor Máximo: 8
Média: 5.333333333333333
Desvio Padrão: 2.0548046676563256
Matriz:
[3, 5, 8]
Média dos elementos é maior que três.
Valor Mínimo: 3
Valor Máximo: 10
Média: 5.666666666666667
Desvio Padrão: 2.494438257849294
Matriz:
[3, 5, 8]
[4, 4, 10]
Média dos elementos é maior que três.
Valor Mínimo: 3
Valor Máximo: 10
Média: 6.666666666666667
Desvio Padrão: 2.5385910352879693
Matriz:
[3, 5, 8]
[4, 4, 10]
[8, 10, 8]
Matriz final:
[3, 5, 8]
[4, 4, 10]
[8, 10, 8]


## Dica do professor

In [ ]:
import numpy as np

matriz = np.zeros([3, 3])

linha = 2
coluna = 1

matriz[linha, coluna] = 1
print(matriz)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]]


## Segunda tentativa

A cada mudança do número da matriz, tirar a média da matriz e verificar se é maior que 3, caso positivo parar e mostrar o valor máximo, mínimo, média e desvio padrão.

In [ ]:
import random
import numpy as np

# Cria uma matriz 3x3 de zeros
matriz = np.zeros((3, 3))

# Preenche a matriz com números aleatórios de 0 a 10
for linha in range(3):
    for coluna in range(3):
        novo_valor = random.randint(1, 10)
        matriz[linha, coluna] = novo_valor
        media_atual = np.mean(matriz)
        print(f"Novo valor: {novo_valor}, Média: {media_atual}")

        if media_atual > 3:
            print("\nMédia atual ", media_atual, " é maior que 3. Parando.")
            print("Valor Mínimo: ", np.min(matriz))
            print("Valor Máximo: ", np.max(matriz))
            print("Média: ", np.mean(matriz))
            print("Desvio Padrão: ", np.std(matriz))
            break
    else:
        continue  # Executa se o loop interno não for interrompido
    break  # Executa se o loop interno for interrompido

print("\nMatriz Final:")
print(matriz)

Novo valor: 4, Média: 0.4444444444444444
Novo valor: 7, Média: 1.2222222222222223
Novo valor: 3, Média: 1.5555555555555556
Novo valor: 2, Média: 1.7777777777777777
Novo valor: 5, Média: 2.3333333333333335
Novo valor: 3, Média: 2.6666666666666665
Novo valor: 3, Média: 3.0
Novo valor: 10, Média: 4.111111111111111

Média atual  4.111111111111111  é maior que 3. Parando.
Valor Mínimo:  0.0
Valor Máximo:  10.0
Média:  4.111111111111111
Desvio Padrão:  2.7666443551086073

Matriz Final:
[[ 4.  7.  3.]
 [ 2.  5.  3.]
 [ 3. 10.  0.]]


# Outras matrizes NumPy

In [ ]:
import numpy as np

#Definindo-se uma matriz de zeros
matriz = np.zeros([3, 3], dtype = int)
#Definindo-se uma matriz de unidades
matriz = np.ones([5, 5])
#Definindo-se uma matriz identidade
matriz = np.identity(7)
matriz = np.eye(3)

print(matriz)
print(type(matriz))
print(matriz.dtype)
print(len(matriz))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
<class 'numpy.ndarray'>
float64
3


In [ ]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__ar