

*   **Nome:** Eduardo Lopes de Oliveira
*   **RA:** 161490336


In [ ]:
import numpy as np
import random

array = np.zeros([3,3,3])

flag = False
for a in range(0,3):
    for l in range (0,3):
        for c in range (0,3):
            item = random.randint(1,10)
            array [a, l, c] = item
            if np.mean(array[a,l,c])>5:
                flag = True
                break
        if flag == True:
            break
        else :
            print(f'linha {l+1} concluida')

print(array)

[[[5. 9. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[4. 5. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[8. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


# Algumas Estrutus de Dado - Listas, Dicionários e Tuplas

In [ ]:
# String
nome = 'João'
frase = nome + ' é de Telecom'
print(frase[0:4])

João


In [ ]:
# Listas
lista = ['João', int(5), 2/3]

lista.append('Maria')
lista.append(1.5)

lista.pop(3) #Remove o item da 4ª posição, no caso Maria
lista.remove('João')
print(lista)

[5, 0.6666666666666666, 1.5]


In [ ]:
# Dicionário

dicionario = {'cor':'vermelho',
              'ano':2018}
dicionario = dict(name = 'João', idade = 36)

carro = {
    'marca' : 'Ford',
    'eletrico' : False,
    'ano' : 2020,
    'cor' : ['vermelhor', 'prata', 'preto']

}

print('Esse carro é da marca', carro['marca'], 'e do ano', carro['ano'])

print(dicionario)
print(dicionario['name'])
print(dicionario['name'][0])

Esse carro é da marca Ford e do ano 2020
{'name': 'João', 'idade': 36}
João
J


In [ ]:
# Tupla

tupla = (1, 2, 3)
tupla = ('João', 1, 2, 2/3)

print(tupla)
print(tupla[0])

('João', 1, 2, 0.6666666666666666)
João


# Utilizando-se Funções no Python

In [ ]:
def funtion(name):
  print('Seu nome é', name)

a = 'Maria'

funtion(a)

Seu nome é Maria


In [ ]:
def operacao(n1, n2, operador):
  a = int(n1)
  b = int(n2)
  if operador == 'soma':
    return a + b
  if operador == 'multiplição':
    return a*b
  else:
    print('Não temos essa operação')


operacao(2, 3, 'soma')

5

#Exercício - Como Utilizar Funções

Crie uma lista com diversos elementos de uma sacola de compras. Utilize uma função para se remover os itens da sacola que o usuário quiser remover. Interaja com o usuário por meio do comando 'input' três vezes.
Caso o usuário escolha 'qualquer', remove o último item da sacola.

In [ ]:
lista = ['Caderno', 'Lápis', 'Caneta', 'Borracha', 'Calculadora']

def tirar(item):
  lista.remove(str(item))

contagem = 0

while contagem < 3:
  coisa = input('Qual item você deseja retirar da lista? ')
  if coisa in lista:
    if coisa == 'qualquer':
      lista.pop(-1)
      print(lista)
      contagem +=1
    else:
      tirar(coisa)
      print(lista)
      contagem +=1
  else:
    print(coisa, 'não está na lista')
    contagem +=1


Qual item você deseja retirar? varinha
varinha não está na lista
Qual item você deseja retirar? camisinha
camisinha não está na lista
Qual item você deseja retirar? bora
bora não está na lista


## Resolução do professor

In [ ]:
sacola = ['leite', 'arroz', 'maça', 'detergente']

def function(sacola, item):
  if item in sacola:
    sacola.remove(item)
  else:
    print('O item', item, 'não está na sacola')

count = 3

while count > 0:
  print('Os itens da sacola são: ', sacola)
  item = input('\n Digite o item a ser retirado\n')
  if item == 'qualquer':
    sacola.pop()
  else:
    function(sacola, item)
  count -= 1


Os itens da sacola são:  ['leite', 'arroz', 'maça', 'detergente']

 Digite o item a ser retirado
leite
Os itens da sacola são:  ['arroz', 'maça', 'detergente']

 Digite o item a ser retirado
maça
Os itens da sacola são:  ['arroz', 'detergente']

 Digite o item a ser retirado
detergente
